spring:
  cloud:
    stream:
      rabbit:
        bindings:
          consumer-in-0:
            consumer:
              exchangeType: fanout
      bindings:
        consumer-in-0:
          destination: test
  application:
    name: consumer-service